# Generated by Django 3.1.1 on 2020-12-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
    ]
