# Generated by Django 3.1.2 on 2020-12-23 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20201221_2349'),
        ('song', '0002_auto_20201222_1553'),
    ]

    operations = [
    ]
