# Generated by Django 3.1.2 on 2020-12-26 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_merge_20201223_1053'),
        ('song', '0003_merge_20201223_1321'),
    ]

    operations = [
    ]
